basic.showString("group")
basic.pause(100)
basic.showNumber(7)
basic.pause(100)
basic.showString("or NGGYU ")
basic.pause(200)
music.playTone(233, music.beat(BeatFraction.Quarter))
music.playTone(262, music.beat(BeatFraction.Quarter))
music.playTone(277, music.beat(BeatFraction.Quarter))
music.playTone(233, music.beat(BeatFraction.Quarter))
music.playTone(349, music.beat(BeatFraction.Half))
music.playTone(349, music.beat(BeatFraction.Half))
basic.pause(200)
music.playTone(311, music.beat(BeatFraction.Half))
basic.pause(200)
music.playTone(208, music.beat(BeatFraction.Quarter))
music.playTone(233, music.beat(BeatFraction.Quarter))
music.playTone(262, music.beat(BeatFraction.Quarter))
music.playTone(208, music.beat(BeatFraction.Quarter))
music.playTone(311, music.beat(BeatFraction.Half))
music.playTone(311, music.beat(BeatFraction.Half))
music.playTone(277, music.beat(BeatFraction.Half))
music.playTone(262, music.beat(BeatFraction.Half))
music.playTone(233, music.beat(BeatFraction.Half))
